name: LFM
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.10
  - cudatoolkit=11.3
  - pip
  - pytorch=1.11.0
  - pytorch-mutex=1.0=cuda
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - pip:
    - numpy==1.22.0
    - pandas
    - matplotlib
    - scikit-learn
    - scipy
    - grpcio
    - opencv-python
    - tensorboard
